### PR TITLE
Ods Examples from Deadalus and profile slice tweak

### PR DESCRIPTION
**Pull request by APageNHS**

### CODE REVIEW

**Review by digitalhealthmartin — COMMENTED** [review]
- Want to make sure that the file format shouldn't be something like Organization-ODS-etc to follow how the StructureDefinitions go.

- Should the assigner 'BSA' also have its corresponding ODS code?

- The country element is populated as 'ENGLAND' but I think ODS mentioned that they don't share the country info in the address (might want to check)

- What would the known/potential use-cases/reasons for allowing Organization.extension:organizationPeriod? Also for OrganizationAffiliation.period.

**Comment by APageNHS** [comment]
> * Want to make sure that the file format shouldn't be something like Organization-ODS-etc to follow how the StructureDefinitions go.
> * Should the assigner 'BSA' also have its corresponding ODS code?
> * The country element is populated as 'ENGLAND' but I think ODS mentioned that they don't share the country info in the address (might want to check)
> * What would the known/potential use-cases/reasons for allowing Organization.extension:organizationPeriod? Also for OrganizationAffiliation.period.

1) For now it's probably not a blocker but I agree and think it needs revisiting, as the original plan for the repo was just examples prefixed with the Program e,g, FGM/CPIS/MCED, and we've now got different England assets

2) I hadn't even noticed that, but that'll be coming from the Organisation.AssigingAuthorityName, and they just have text

3) I'd need to go abck through, I think the country is there in the tables, not in the xml, and thus is now no longer NOT NULL?

4) From Dougal:
England-OrganizationAffiliation-ODS – constrains the resource to not include the standard R4 period”
            {
                "id": "OrganizationAffiliation.period",
                "path": "OrganizationAffiliation.period",
                "max": "0"
            },
 
This will hinder the use of these resources because it makes the basic period information unavailable to clients that don’t know/care about the local extension (we should be aiming to not require every client to be customised around the extensions if they have no need for the granularity/additional information that the extension carries) - Please can this constraint be removed (optional fields should be populated where the data is available – and in this case the data is available) .

TBH @ryma2fhir did question if I'd been too strict on this originally, so I'm happy to relax it, and i've added text to point towards the typedperiod extension

**Comment by digitalhealthmartin** [comment]
> > * Want to make sure that the file format shouldn't be something like Organization-ODS-etc to follow how the StructureDefinitions go.
> > * Should the assigner 'BSA' also have its corresponding ODS code?
> > * The country element is populated as 'ENGLAND' but I think ODS mentioned that they don't share the country info in the address (might want to check)
> > * What would the known/potential use-cases/reasons for allowing Organization.extension:organizationPeriod? Also for OrganizationAffiliation.period.
> 
> 1. For now it's probably not a blocker but I agree and think it needs revisiting, as the original plan for the repo was just examples prefixed with the Program e,g, FGM/CPIS/MCED, and we've now got different England assets
> 2. I hadn't even noticed that, but that'll be coming from the Organisation.AssigingAuthorityName, and they just have text
> 3. I'd need to go abck through, I think the country is there in the tables, not in the xml, and thus is now no longer NOT NULL?
> 4. From Dougal:
>    England-OrganizationAffiliation-ODS – constrains the resource to not include the standard R4 period”
>    {
>    "id": "OrganizationAffiliation.period",
>    "path": "OrganizationAffiliation.period",
>    "max": "0"
>    },
> 
> This will hinder the use of these resources because it makes the basic period information unavailable to clients that don’t know/care about the local extension (we should be aiming to not require every client to be customised around the extensions if they have no need for the granularity/additional information that the extension carries) - Please can this constraint be removed (optional fields should be populated where the data is available – and in this case the data is available) .
> 
> TBH @ryma2fhir did question if I'd been too strict on this originally, so I'm happy to relax it, and i've added text to point towards the typedperiod extension

Points 1 and 2 - that's fine for now. 
Point 3 - it's not 'NOT NULL' anymore in the mapping table (but I can remove country as a FHIR element in the table).
Point 4 - That's fine, makes sense especially if they want it that way, as long as some text is added to explain it in the table.

I do have another point to make. At first I was fine with your change to updating the Profile URLs in the CapabilityStatement. However, today I am having second thoughts. As these are 'Test Profiles', and considering that a CapabilityStatement is something that a supplier has to conform to, shouldn't it be the case that they only 'officially' conform to UK Core profiles?

**Review by digitalhealthmartin — APPROVED** [review]
Approved. On the basis that the CapabilityStatement update is purely for use within this repo's validation and not used by any programmes. The ODS CapabilityStatement is currently using UK Core Profiles as was agreed as a provisional approach in DA.

**Pull request merged**
