### PR TITLE
First Multi cancer early detection example

### PR DESCRIPTION
**Pull request by APageNHS**
Failing validation due to meta.profile, but we can expect that in real world examples (maybe turn off erroring for this repo), and MessageHeader.eventCoding...

UKCore binding is Example to 2 NHSD codesystems, https://simplifier.net/guide/uk-core-implementation-guide-stu3-sequence/Home/Terminology/AllValueSets/ValueSet-UKCore-MessageEvent?version=1.7.0, validation has errored with a snomed ct one - 371528001, concept id is valid and active

### CODE REVIEW

**Comment by omarisgreat** [comment]
The MessageHeader eventCoding issue may be being raised as there isn't a MessageDefinition for the SNOMED code you've provided so it can't validate the resources within the message bundle are the ones needed

**Comment by omarisgreat** [comment]
> The MessageHeader eventCoding issue may be being raised as there isn't a MessageDefinition for the SNOMED code you've provided so it can't validate the resources within the message bundle are the ones needed

The specific error message is coming from the [MessageDefinitionApplier.kt](https://github.com/NHSDigital/IOPS-FHIR-Validation-Service/blob/91a0f9a2565b9c97f572766394908ea32cd616fc/src/main/kotlin/uk/nhs/england/fhirvalidator/service/MessageDefinitionApplier.kt#L38) in the IOPS-FHIR-Validation-Service.

The validator is definitely trying to apply a message definition for the given event coding. The fact that this does not apply while in UKCore is a separate issue (probably due to some config)

**Comment by DaveBarnet** [comment]
I suppose it could be, but I would expect to validate against a MD if there was one, otherwise just check the message Bundle against the package definitions & some mincing about with terminology. Seems a bit of an overhead to create a MD per event type?

**Comment by omarisgreat** [comment]
> I suppose it could be, but I would expect to validate against a MD if there was one, otherwise just check the message Bundle against the package definitions & some mincing about with terminology. Seems a bit of an overhead to create a MD per event type?

Probably needs an update to the validator then to apply a message definition if found rather than throwing an exception

**Comment by APageNHS** [comment]
Test PR, Dave's is the one to review

**Pull request closed without merging**
